[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo_mysql", "php82Extensions.bcmath", "php82Extensions.fileinfo", "php82Extensions.tokenizer", "php82Extensions.mbstring", "php82Extensions.openssl", "php82Extensions.curl", "nodejs_20", "npm"]

[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist",
    "npm install",
    "npm run build",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache",
    "php artisan storage:link"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
